#!/bin/sh

usage () {
  echo "usage: FILE1 FILE2"
  exit 1
}

dump () {
  hexdump -ve '"%07.7_ax  " 1/1 "%_c" "\n"'
}

if ! [ -e "$1" ]; then
  echo invalid file $1
  usage
fi

if ! [ -e "$2" ]; then
  echo invalid file $2
  usage
fi

#f1size=$(cat $1 | wc -c)
#f2size=$(cat $2 | wc -c)
#
#if [ -z "$f1size" -o -z "$f2size" -o "$f1size" != "$f2size" ]; then
#  printf 'files are not the same size: "%s" != "%s"\n' "$f1size" "$f2size"
#  usage
#fi

set -e

t1=$(mktemp)
cat $1 | dump > $t1
t2=$(mktemp)
cat $2 | dump > $t2

set +e

diff $t1 $t2
result=$?

rm -f $t1 $t2
