#!/bin/sh

fmt='%C(bold blue)%h%C(reset) - %C(bold green)(%ar,%an,%p)%C(reset) %C(white)%s%C(reset) %C(bold yellow)%d%C(reset)'
git log --graph \
        --topo-order \
        --abbrev-commit \
        --format=format:"$fmt" \
        $@
