#!/bin/bash

source cantora-shlib.sh

push () {
  dir_arg $1
  pushd $1 > /dev/null
}

pop () {
  popd > /dev/null
}

git --version > /dev/null 2>&1
if [ $? -ne 0 ]; then
  err_exit 'git is not installed'
fi

if [ -f '.gitstat-dirs-ignore' ]; then
  IGNORE=$(realpath .gitstat-dirs-ignore)
fi

for i in */.git/..; do
  push $i
  NAME=$(basename $(pwd))
  if [ -f $IGNORE ]; then
    grep "$(printf '^%s *$' $NAME)" $IGNORE > /dev/null
    if [ $? -eq 0 ]; then
      printf '(ignoring %s)\n' $NAME
      pop
      continue
    fi
  fi

  printf '<%s>\n' $NAME
  gitstat 2
  pop  
done
