#!/bin/sh

if [ "$(uname)" = "Darwin" ]; then
	BKP_DIR=$(mktemp -d -t tmp)
else
	BKP_DIR=$(mktemp -d)
fi

FILES=$BKP_DIR/gpg-files
mkdir $FILES
cp ~/.gnupg/pubring.gpg $FILES
cp ~/.gnupg/secring.gpg $FILES
gpg --export-ownertrust > $FILES/ownertrust-gpg.txt

etype=aes-256-cbc

sh -c "cd $BKP_DIR && tar -cjvf gpg.tar.bz2 gpg-files"
out=gpg-$(date +%Y%m%d%H%M%S).tar.bz2.${etype}

openssl enc \
	-${etype} \
	-in $BKP_DIR/gpg.tar.bz2 \
	-out $out
if [ $? -ne 0 ]; then
	echo "failed to encrypt"
	exit 1
fi

cd $BKP_DIR 
rm gpg.tar.bz2
rm -f gpg-files/*
rmdir gpg-files
