#!/bin/bash

if [ -z "$1" -o -z "$2" ]; then
  echo "usage: $0 AUTHOR PROJECT_NAME"
  exit 1
fi

echo "/* "
echo " * Copyright $(date +%Y) $1"
cat <<HEADER
 * This file is part of $2.
 *
 * $2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * $2 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with $2.  If not, see <http://www.gnu.org/licenses/>.
HEADER
echo " */"

