#!/bin/sh

if [ "$#" -lt 3 ]; then
  echo 'usage: PORT DHOST DPORT'
  exit 1
fi

set -e

iptables -t nat \
         -A OUTPUT \
         -p tcp \
         --dport "$1" \
         -j DNAT \
         --to-destination "${2}:${3}"

echo iptables -A FORWARD \
         -p tcp \
         -d $3 \
         --dport $4 \
         -m state \
         --state NEW,ESTABLISHED,RELATED \
         -j ACCEPT
