#!/bin/bash

TMP1=$(mktemp)
TMP2=$(mktemp)
TMP3=$(mktemp)

tree -a -F --charset ASCII | cut -b 1 --complement > $TMP1

cat $TMP1 | sed 's/^\(--\|  \)/\*/' > $TMP2

until diff $TMP1 $TMP2 > /dev/null 2>&1; do
  cat $TMP2 | sed 's/^\(\*\+\) [`| ]\(--\|  \)/\1\*/' > $TMP1
  mv $TMP2 $TMP3
  mv $TMP1 $TMP2
  mv $TMP3 $TMP1
done

cat $TMP2 | tail -n +2 | head -n -1




