#!/usr/bin/env python2

from subprocess import Popen, PIPE

client_sockets = []
match = 0

ns = Popen(["netstat", "-an", "--unix"], stdout=PIPE)
output = ns.communicate()[0]
for line in output.split('\n'):
	print line
	if line.find("X11-unix") != -1:
		match = 1
		print 'match'
	elif match:
		match = 0
		inode = line.split()[6]
		#print('extract inode %s' % (inode))
		client_sockets.append(inode)

#print "-"*80
lsof = Popen(["lsof", "-U", "+c0", "-w"], stdout=PIPE)
output = lsof.communicate()[0]
for line in output.split('\n'):
	try:
		inode = line.split()[7]
		if inode in client_sockets:
			print line
	except:
		pass
