#!/usr/bin/python3
from http.server import HTTPServer, SimpleHTTPRequestHandler
import sys

def run():
  if len(sys.argv) < 2:
    port = 8000
  else:
    port = int(sys.argv[1])

  server_address = ('127.0.0.1', port)
  httpd = HTTPServer(server_address, SimpleHTTPRequestHandler)
  httpd.serve_forever()

if __name__ == '__main__':
  run()
