#!/usr/bin/env python2
import BaseHTTPServer, SimpleHTTPServer
import ssl
import os.path

# openssl genrsa -out server.key 1024
# openssl req -new -key server.key -out server.csr
# openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
# openssl x509 -inform PEM -in server.crt -out server.pem

confdir = os.path.expanduser('~/install/simplessl')
cert = os.path.join(confdir, 'server.crt')
key = os.path.join(confdir, 'server.key')

addr = ('0.0.0.0', 4443)

httpd = BaseHTTPServer.HTTPServer(addr, SimpleHTTPServer.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket(httpd.socket,
                               certfile=cert,
                               keyfile=key,
                               server_side=True)
httpd.serve_forever()
