#!/usr/bin/env python2
import BaseHTTPServer, SimpleHTTPServer
import ssl

# openssl genrsa -out server.key 1024
# openssl req -new -key server.key -out server.csr
# openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
# openssl x509 -inform PEM -in server.crt -out server.pem

httpd = BaseHTTPServer.HTTPServer(('localhost', 443), SimpleHTTPServer.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket (httpd.socket, certfile='/tmp/simplehttp/server.crt', keyfile='/tmp/simplehttp/server.key', server_side=True)
httpd.serve_forever()
